from __future__ import annotations

APP_VERSION = "V30.0"
APP_VERSION_NAME = "V30 測試版"
APP_BUILD_DATE = "2026-09-05"

DEFAULT_BATTERY_THRESHOLD = 89
DEFAULT_BATTERY_PRIORITY_THRESHOLD = 40
SMART_DISPATCH_CANDIDATE_LIMIT = 10

YOUBIKE_STATION_CATALOG_URL = "https://apis.youbike.com.tw/json/station-min-yb2.json"
YOUBIKE_BATTERY_URL = "https://apis.youbike.com.tw/api/front/bike/lists"

BATTERY_CACHE_TTL_SECONDS = 30
BATTERY_STALE_TTL_SECONDS = 300
BATTERY_REQUEST_TIMEOUT_SECONDS = 12
BATTERY_MAX_ATTEMPTS = 3
BATTERY_MAX_CONCURRENCY = 4
BATTERY_RETRY_BACKOFF_SECONDS = (0.3, 0.8)

STATION_CATALOG_TTL_SECONDS = 6 * 60 * 60
STATION_MATCH_THRESHOLD = 0.72
STATION_MATCH_AMBIGUITY_MARGIN = 0.035
